# Generated by Django 3.2.25 on 2024-11-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_number', models.IntegerField()),
                ('owner', models.CharField(choices=[('first-owner', 'first-owner'), ('second-owner', 'second-owner')], default='fisrt-owner', max_length=200)),
                ('running_km', models.FloatField()),
                ('price', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
