# Generated by Django 3.2.25 on 2024-11-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_item',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('electric', 'electric')], default='petrol', max_length=200),
        ),
    ]
